[phases.setup]
nixPkgs = ["postgresql", "nodejs"]
aptPkgs = ["postgresql-client"]

[phases.build]
cmds = [
  "cd server && npm install --legacy-peer-deps",
  "cd server && npx prisma generate",
  "cd server && npx prisma db push --accept-data-loss"
]

[start]
cmd = "cd server && npm start"

