[phases.setup]
nixPkgs = ["postgresql"]
aptPkgs = ["postgresql-client"]

[phases.build]
cmds = [
  "npm install --legacy-peer-deps",
  "npx prisma generate",
  "npx prisma db push --accept-data-loss"
]

[start]
cmd = "npm start"

